name: Go CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# env:
#   IMAGE_NAME: your-dockerhub-username/go-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Download dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test ./...

    # - name: Build Docker image
    #   run: docker build -t ${{ env.IMAGE_NAME }} .

    # - name: Login to DockerHub
    #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # - name: Push Docker image
    #   run: docker push ${{ env.IMAGE_NAME }}

    # - name: Deploy to EC2
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USER }}
    #     key: ${{ secrets.EC2_PRIVATE_KEY }}
    #     script: |
    #       docker pull ${{ env.IMAGE_NAME }}
    #       docker stop go-app || true
    #       docker rm go-app || true
    #       docker run -d --name go-app -p 80:8080 ${{ env.IMAGE_NAME }}
